#! /bin/sh
set -e

cd /org/bugs.debian.org/versions/indices

ARCHIVES='ftp' # security -- should be included too, but too difficult to deal with

../bin/build-versions-db versions.idx versions_time.idx \
			 /etc/debbugs/indices/ftp \
			 oldstable stable proposed-updates \
			 testing \
			 testing-proposed-updates \
			 unstable \
			 experimental;
